FROM node:lts-alpine3.9

# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# Install app dependencies
COPY package.json /usr/src/app/
RUN npm update
RUN npm install

# Bundle app source
COPY . /usr/src/app

CMD [ "npm", "test" ]